---
title: "Activity: Final Project"
author: "Jason Abu"
date: "04/03/2020"
output: html_notebook
---



* Guiding Question - How are youtubers getting plenty of views?

* I found these data sources from an website called Kaggle.

* The dataset 'YouTube Top 4000 Channels based on subscribers' was collected and is being maintained by Libin Mathew. The dataset 'YouTube channels ~100000' was collected and is being maintained by Ilya Babikov. The data "YouTube Trending Video Statistics with Subscriber Data" is was collected and is being maintained by an unknown coder that identifies himself on Kaggle as Mr. SG.

* "YouTube Top 4000 Channels based on subscribers" was created a year ago 2019-04-18.
"YouTube channels ~100000" was created 2018-11-15. "YouTube Trending Video Statistics with Subscriber Data" was created 2018-03-24. These datasets purposes were not presented but they all seem to serve the purpose of giving indepth information about Youtube.

* Each case in "YouTube Top 4000 Channels based on subscribers" represent the top channels based on subscriber number and also number of views. There are over a thousand cases in this dataset. 
Each case in "YouTube channels ~100000" represents various youtube channels and their number of followers. There are over a thousand cases in this dataset.
Each case in "YouTube Trending Video Statistics with Subscriber Data" represents the trending youtube videos with respect to subscribers. There is also over a thousand cases in this dataset as well.